version: "3.9"

services:
  postgres:
    restart: unless-stopped
    image: postgres:latest
    environment:
      POSTGRES_DB: "testWB"
      POSTGRES_USER: "dobb2"
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/1.sql
    ports:
      - "54320:5432"
